title: "Kerpen Rainwater Management Web App"
description: "A tool to explore sustainable rainwater and stormwater management solutions for Kerpen."
theme: minima

# Navigation links for the header
header_pages:
  - index.md
  - about.md
  - solutions.md
  - imperviousness.md
  - form.html

markdown: kramdown
